### ISSUE TITLE
Unable to verify the downloaded file 

### ISSUE THREAD

**Issue by T-e-j-k-u-m-a-r** [elaichenkov/cy-verify-downloads#1]
Hi, 

Thanks for the contribution!

I'm unable to verify the downloaded file where I used another npm package cypress-downloadfile
Here is the video recording of the issue: https://www.youtube.com/watch?v=Gpv8wCdJsKo
Please go through it and let me know the solution. 

Note: I feel its all about the location where file is downloaded and the location where the verification is being done. 

Regards,
Tejkumar

**Comment by elaichenkov** [comment]
Hi!
Thanks for the well-described issue with the video. So, the problem in the `cypress-downloadfile` package, it downloads the file outside the cypress directory, but the `cy-verify-downloads` package expects that downloads folder will be in the cypress directory. Hence, you have to provide this path for the `Downloads` folder for the `cypress-downloadfile` package to solve the problem.

In your test:

```javascript
    //                                                                                                                                   👇 directory 'cypress/downloads'
    cy.downloadFile('https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg','cypress/downloads','example.jpg');
```
