### ISSUE TITLE
Problems with adding polyfill

### ISSUE THREAD

**Issue by Agentrapyntsel** [elaichenkov/cy-verify-downloads#101]
Hi, Thanks for the contribution.
as some another guys i having a problem with "fs" error. but i cant realize how to apply the decision with polyfill because i having such settings in setupNodeEvents as you can see at the picture and i catching TS errors. Do you have some thoughts how to attach polyfill code here?
And is  it possible that in the future major versions this problem will be solved in some maybe another way?
![settings](https://user-images.githubusercontent.com/83089943/229539819-61e37223-29a5-4dfa-aafb-c1882740d18e.png)

**Comment by Agentrapyntsel** [comment]
thanks for your answer. i added NodePolyfillPlugin, but still catching error
![support](https://user-images.githubusercontent.com/83089943/230303042-556f190f-2613-467d-9cb2-d23b501d
![error](https://user-images.githubusercontent.com/83089943/230303080-626f6271-b24b-4be7-8418-da333a324782.png)
d740.png)

**Comment by Agentrapyntsel** [comment]
![support](https://user-images.githubusercontent.com/83089943/230303173-229dfc21-5025-4335-be35-962242ac6366.png)

**Comment by Agentrapyntsel** [comment]
i solved this problem by adding to webpackOptions:
  resolve: {
            extensions: ['.ts', '.js'],
            fallback: {
                fs: false ,
            },
        },

**Comment by elaichenkov** [comment]
@Agentrapyntsel 
Thank you for sharing this!
