### ISSUE TITLE
While using in ".ts" file throwing "File '/Users/[userdir]/node_modules/cy-verify-downloads/src/index.d.ts' is not a module.ts(2306)"

### ISSUE THREAD

**Issue by Ramakanta5555** [elaichenkov/cy-verify-downloads#129]
![image](https://github.com/elaichenkov/cy-verify-downloads/assets/103567038/ae5fe959-8795-4371-abbe-4e460722861f)
Please refer to this image.

This error is not coming in ".js" extension file.

**Comment by 7coil** [comment]
It seems to me that `index.d.ts` doesn't actually export anything, and only extends Cypress. I'll give writing types a go and then attempt a PR.

**Comment by elaichenkov** [comment]
Actually, it should not be exported. Have you updated your `tsconfig` accordingly? Even more, can you please provide more information on it (configs, screenshots, and so on)? I've just created the Cypress project and added the library by the instructions and everything works with no errors.

**Comment by krisztianb** [comment]
I have this issue too.

This module does export several things: https://github.com/elaichenkov/cy-verify-downloads/blob/master/src/index.js#L78

But the exports are not visible in the type definition file. Therefore TSC is complaining about it not being a module.

I guess you wrote the type definition file yourself? Here is an example for a type definition file I once created where the module is exporting a function: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/12342c0ca0093458574699a44de17ba01b4386f2/types/hyphen/index.d.ts

**Comment by elaichenkov** [comment]
Hi all,
Sorry, I totally missed this part somehow. However, I fixed the issue and released a new version with a fix. So, please update the package to the `0.2.0` version and happy testing.

**Comment by krisztianb** [comment]
That was fast. Thank you.
