### ISSUE TITLE
Would be good to be able to use wildcards in filename

### ISSUE THREAD

**Issue by iherbak** [elaichenkov/cy-verify-downloads#13]
We are downloading files containing timestamp, so it is not predictible to have the exact filename for verifying.

Would be good to use * or ? or maybe regex to watch for file.

Thanks

**Comment by elaichenkov** [comment]
It will be done in part of #11

**Comment by elaichenkov** [comment]
Added in the [0.1.1](https://github.com/elaichenkov/cy-verify-downloads/releases/tag/0.1.1). Please, let me know if something doesn't work as expected. Also, don't forget to give it a start.
