### ISSUE TITLE
Doesn't work with "cypress-vite" preprocessor

### ISSUE THREAD

**Issue by sigerello** [elaichenkov/cy-verify-downloads#134]
While it works fine with default Cypress preprocessor, it doesn't work with [cypress-vite](https://github.com/mammadataei/cypress-vite) preprocessor.
I get the following error:
```
TypeError: join is not a function
```

It seems it cannot resolve the module in your plugin:
```
const { join } = require('path');
```
All other tests, which don't use `verifyDownload` command, work without any issues.
I don't know whether I'd better submit the issue in **cypress-vite** repo, but maybe you can suggest how to fix it?
Maybe some additional vite configuration is needed?

**Comment by elaichenkov** [comment]
Hey,
Can you please provide a reproducible example? However, it seems that adding node polyfills will solve the problem. So, please try to install the `vite-plugin-node-polyfills` package and add all needed polyfills in your `vite.config.ts` file. For instance:

1. Install node polyfills package
```bash
npm install --save-dev vite-plugin-node-polyfills
```

2. Add `nodePolyfills` to your config file.
```ts
import { defineConfig } from 'vite';
import { nodePolyfills } from 'vite-plugin-node-polyfills';

export default defineConfig({
  plugins: [
    nodePolyfills({
      include: ['path', 'fs', 'crypto', 'stream'],
    }),
  ],
});

```

**Comment by sigerello** [comment]
@elaichenkov Thanks for you help!
Here is a repo with reproducible example:
https://github.com/sigerello/cy-verify-downloads-issue-134

I've just borrowed the site folder and the test example from your repo.
You can clone it and then run:

```
npm ci
npm test
```

Your suggestion of using `vite-plugin-node-polyfills` unfortunately did not help.
After adding it I get the following error:

```
Cannot destructure property 'existsSync' of 'empty_1' as it is null.
```

**Comment by elaichenkov** [comment]
Hey @sigerello 
Thank you for the example and meaningful error. I've updated the package to make it work with Vite. So, please update the version to 0.1.17 and enjoy testing. Have a great weekend.

P.S. Keep in mind that the `nodePolyfills` with the mentioned above values is required anyway.

**Comment by sigerello** [comment]
@elaichenkov Awesome! Works like a charm!
Thanks a lot for your quick response and provided fix! 🙏🏼
Glory to Ukraine! 🇺🇦
