### ISSUE TITLE
TypeError: crypto.randomBytes is not a function

### ISSUE THREAD

**Issue by zy4** [elaichenkov/cy-verify-downloads#137]
Hi!

I am using this library with typescript and followed the instructions and also this [comment](https://github.com/elaichenkov/cy-verify-downloads/issues/51#issuecomment-1237978973)

The error happens when 

```typescript
cy.verifyDownload('.png', { contains: true });
```

is called.

Any ideas? Thanks!

**Comment by elaichenkov** [comment]
Hey,
Can you please provide more information on it?

- Node version:
- Cypress version:
- cy-verify-downloads version:
- Your config file:

**Comment by zy4** [comment]
Sure!

Node: 18, cypress: 13, cy-verify-downloads: 0.2.0

Here is the config:

const { defineConfig } = require('cypress');
const createBundler = require('@bahmutov/cypress-esbuild-preprocessor');
const preprocessor = require('@badeball/cypress-cucumber-preprocessor');
const addCucumberPreprocessorPlugin =
  require("@badeball/cypress-cucumber-preprocessor").addCucumberPreprocessorPlugin;
const createEsbuildPlugin = require('@badeball/cypress-cucumber-preprocessor/esbuild');
const { NodeModulesPolyfillPlugin } = require('@esbuild-plugins/node-modules-polyfill');
const { verifyDownloadTasks } = require('cy-verify-downloads');

const setupNodeEvents = async (on, config) => {
  await preprocessor.addCucumberPreprocessorPlugin(on, config);
  on(
    'file:preprocessor',
    createBundler({
      plugins: [NodeModulesPolyfillPlugin(), createEsbuildPlugin.default(config)],
    })
  );
  await addCucumberPreprocessorPlugin(on, config);
  on('task', verifyDownloadTasks);
  return config;
};

**Comment by elaichenkov** [comment]
Your config looks fine. There's only one thing that is wrong. You are invoking `addCucumberPreprocessorPlugin` function twice. But, it should not be a problem. Moreover, I've just tested and it worked as expected. 

Here is the config I tried:
```js
// cypress.config.js
const { defineConfig } = require('cypress');
const createBundler = require('@bahmutov/cypress-esbuild-preprocessor');
const { addCucumberPreprocessorPlugin } = require('@badeball/cypress-cucumber-preprocessor');
const { createEsbuildPlugin } = require('@badeball/cypress-cucumber-preprocessor/esbuild');
const { NodeModulesPolyfillPlugin } = require('@esbuild-plugins/node-modules-polyfill');
const { verifyDownloadTasks } = require('cy-verify-downloads');

const setupNodeEvents = async (on, config) => {
  on(
    'file:preprocessor',
    createBundler({
      plugins: [NodeModulesPolyfillPlugin(), createEsbuildPlugin(config)],
    }),
  );
  await addCucumberPreprocessorPlugin(on, config);
  on('task', verifyDownloadTasks);
  return config;
};

module.exports = defineConfig({
  e2e: {
    baseUrl: 'https://duckduckgo.com',
    specPattern: '**/*.feature',
    setupNodeEvents,
  },
});
```
<img width="699" alt="image" src="https://github.com/elaichenkov/cy-verify-downloads/assets/29764053/4b0ab172-9db4-453a-9719-a581ff86cd95">

Please, make sure that you added the commands as well.

**Comment by elaichenkov** [comment]
Thank you for the information. I managed to reproduce it. It seems that the problem is with the node polyfill. It doesn't enable a crypto module [by default](https://github.com/remorses/esbuild-plugins/issues/34)...

So, please use another package and configuration:

```js
const { defineConfig } = require('cypress');
const createBundler = require('@bahmutov/cypress-esbuild-preprocessor');
const { addCucumberPreprocessorPlugin } = require('@badeball/cypress-cucumber-preprocessor');
const { createEsbuildPlugin } = require('@badeball/cypress-cucumber-preprocessor/esbuild');
const { verifyDownloadTasks } = require('cy-verify-downloads');

// Please, install the esbuild-plugin-polyfill-node package
const { polyfillNode } = require('esbuild-plugin-polyfill-node');

const setupNodeEvents = async (on, config) => {
  on(
    'file:preprocessor',
    createBundler({
      plugins: [
        // Add the polyfillNode plugin to the esbuild bundler
        polyfillNode({
          polyfills: {
            crypto: true,
          },
        }),
        createEsbuildPlugin(config),
      ],
    }),
  );
 
  await addCucumberPreprocessorPlugin(on, config);
  on('task', verifyDownloadTasks);
  return config;
};
```

Let me know, if there is anything else. Also, don't forget to give a star for the project.

**Comment by zy4** [comment]
Thanks, that worked for me! I think the README should be updated with this polyfill example, rather than the current one...
