### ISSUE TITLE
Unable to addcustom command for verify downloads 

### ISSUE THREAD

**Issue by Vijayapriyacs** [elaichenkov/cy-verify-downloads#29]
require('cy-verify-downloads').addCustomCommand()

I have installed  cy-verify-downloads and then add the  above mentioned  custom command on command.js file 
But it through  the error as  'cy-verify-downloads is not module' 
So I am unable  to proceed  further please  help me 5o resolve  this error

**Comment by elaichenkov** [comment]
Hey,

Thanks for the filling issue. Can you please add additional information (stack trace, OS, node version, cypress version, cy-verify-downloads version)? Also, it'd be useful to provide the config and command.js file.

**Comment by Vijayapriyacs** [comment]
![20220603_123847](https://user-images.githubusercontent.com/24434428/171805683-81e2b7d0-e51a-4754-8e74-ddce500fe667.jpg)
Plea
![20220603_122227](https://user-images.githubusercontent.com/24434428/171805702-e3aec50c-75ad-4e96-b078-323eda45f07a.jpg)
Se
![Uploading 20220603_122408.jpg…]

**Comment by elaichenkov** [comment]
Thanks for the screenshots. It seems that your last one was not loaded. Are you using TypeScript? If so, did you add types?
https://github.com/elaichenkov/cy-verify-downloads#types

**Comment by Vijayapriyacs** [comment]
Hi Elaichenkov,

Yes I am using typescript,  and I have already  added this line as well ,
dont I need to add the custom  commands then

tsconfig.json file:

{ "compilerOptions": { "types": ["cypress", "cy-verify-downloads"] } }



Still getting the error on the below line

require('cy-verify-downloads').addCustomCommand()

**Comment by Vijayapriyacs** [comment]
Working fine earlier I was  put below code in incorrect command.js file .
require('cy-verify-downloads').addCustomCommand()

**Comment by jyotiagcse** [comment]
I am also facing the same issue. I have installed the package and I am not using javascript
 
![image](https://user-images.githubusercontent.com/58038109/172874458-24f8ec72-5cae-4bf3-b185-ec9ef366f34c.png)

**Comment by Vijayapriyacs** [comment]
This issue was resolved  if you  provide that command  in correct file the
command.js  file you provided  right now is wrong location

**Comment by wawyed** [comment]
This still is an issue if you want to use Typescript. Moving the command to a js file is not a solution.
