### ISSUE TITLE
Test argument "title" should be a string. Received type "object"

### ISSUE THREAD

**Issue by luciarodriguez** [elaichenkov/cy-verify-downloads#3]
Immediately after installing the `cy-verify-downloads` plugin, I started receiving this error message and could not run any further tests:

`TypeError`
`The following error originated from your test code, not from Cypress.`
`  > Test argument "title" should be a string. Received type "object"`

`When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.`

`Cypress could not associate this error to any specific test.`

Here are the steps I followed, as per the instructions in the installation:
1. Run `npm i -D cy-verify-downloads`
2. Added `require('cy-verify-downloads').addCustomCommand();` to `cypress/support/commands.js:`
3. Added the mentioned code to `cypress/plugins/index.js:`

I ran the tests as they were before, and I got the error message. After uninstalling, I didn't get the error anymore.

Can you please take a look and let me know if there's something I'm missing? 

I'm on Cypress version 9.0.0.

**Comment by elaichenkov** [comment]
Hey,

Thanks for raising this issue. I've just double-checked it with the latest version 9.1.1 and everything works like a charm. Even more, based on the error message I can say that there's something wrong with the `mocha` runner. Perhaps, you've provided something unexpected to the `describe` or `it` functions.

**Comment by luciarodriguez** [comment]
@elaichenkov I do use the tag feature for my `it` cases. If I remove the tag while using the verify-downloads plugin, there are no errors, but if I leave the tags, the error comes up. Again, I've no problems with the scripts if I don't have the verify-downloads plugin.

Can you add support for tags, in addition to having a test case name?

**Comment by elaichenkov** [comment]
That's really strange because it shouldn't be related to. Sure, I can take a look at it. Can you please send me a code example of how you're using tags?

**Comment by luciarodriguez** [comment]
This is how my test cases look like:

`it([Tags.P0], "CODE-XXX: Test Case Description", () => {`

There is a `Tags.ts` file under `/cypress/utils` which is just an `enum` with my list of tags.

**Comment by luciarodriguez** [comment]
Thanks @elaichenkov. Are you using enums to retrieve the strings for using the tags? Because I'm still seeing the problem. Can you send me a code sample?

**Comment by elaichenkov** [comment]
Yeah, sure.
Here's a code example:
```typescript
// test.spec.ts
enum Tags {
  'WIP' = 'work in progress',
  'REGRESSION' = 'regression',
  'SMOKE' = 'smoke',
};

describe('Download', () => {
  beforeEach(() => {
    cy.visit('http://localhost:8039')
  })

  it([Tags.SMOKE], "CODE-XXX: Test Case Description", () => {
    cy.get('[data-cy="small"]').click();
    cy.verifyDownload('small-file-10MB.zip')
  })
});
```

![image](https://user-images.githubusercontent.com/29764053/145611349-1f7107d2-e6bc-4102-9ca3-cb27c68bbacd.png)


Also may be useful what I have in plugin:
```typescript
const { isFileExist } = require('cy-verify-downloads');
const tagify = require('cypress-tags');

module.exports = (on, config) => {
    on('task', {
        isFileExist
    })

    on('file:preprocessor', tagify(config))
}
```

**Comment by luciarodriguez** [comment]
Cool, that worked. Thank you!
