### ISSUE TITLE
Issue with 'ERROR: Could not resolve "path", "fs", "crypto"'

### ISSUE THREAD

**Issue by ghostqaAV** [elaichenkov/cy-verify-downloads#37]
Hi @elaichenkov

Good day,
I have a problem with your plugin. 
I use Cypress(10.2.0) + [@badeball/cypress-cucumber-preprocessor](@badeball/cypress-cucumber-preprocessor) >>  [example with esbuild-cjs](https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples/esbuild-cjs)

When I try to install your plugin I get the following error (ERROR: Could not resolve "path", "fs", "crypto")
[Screenshot](https://drive.google.com/file/d/1zawuCye4j4GCPCNHrogX_U_qDJ8AEMBB/view?usp=sharing)

please fix it

**Comment by MaximBelov** [comment]
You can check this PR

https://github.com/elaichenkov/cy-verify-downloads/pull/7

Please try my solution for your case

`npm i https://github.com/MaximBelov/cy-verify-downloads.git#0.1.1 -D`

**Comment by myoanita** [comment]
Hello, I'm facing the same issue like this.
It still not solving my issue after installing 
`npm i https://github.com/MaximBelov/cy-verify-downloads.git#0.1.1 -D`

### This is the error that i've got after installing that :
<img width="922" alt="Screen Shot 2022-08-03 at 15 26 33" src="https://user-images.githubusercontent.com/23337558/182561338-bb09069c-215e-47db-8dea-b7873325380b.png">

**Comment by stass-1** [comment]
@myoanita I realized, this plugin it's not nessesary. You can veryfy downloads with pure cypress. Here my code example:
`const downloadsFolder = Cypress.config('downloadsFolder')`
`cy.get('#download-link').click()`
`cy.readFile(downloadsFolder + '/downloaded_file.xlsx')`
