### ISSUE TITLE
Click to the download link waiting page laod

### ISSUE THREAD

**Issue by jeremy-rafflin** [elaichenkov/cy-verify-downloads#4]
Hi,
I test a file download. It's work fine if I am using 'cypress open', but when I use 'cypress run', I have this error. 
Can I prevent the page load ?
![Capture](https://user-images.githubusercontent.com/5859762/149368796-740a6616-3887-4fc4-a319-3fbb2d0e3348.PNG)

**Comment by elaichenkov** [comment]
Hey,
Thanks for the issue. However, the issue is not related to the plugin. Read more about cypress [here](https://docs.cypress.io/faq/questions/using-cypress-faq#How-do-I-wait-for-my-application-to-load)
