### ISSUE TITLE
Getting ERROR: Could not resolve "crypto" and ERROR: Could not resolve "fs" when running Test

### ISSUE THREAD

**Issue by ayingyong** [elaichenkov/cy-verify-downloads#51]
Hi. i followed every steps mentioned in here https://github.com/elaichenkov/cy-verify-downloads. However, when running my test. It keep on throwing me these errors. Which part that i'm doing wrong here ?
![image](https://user-images.githubusercontent.com/64765489/186647764-886d7835-c9c3-4efc-8aeb-5d568e9df1d7.png)

Cypress version: 10.4.0
cy-verify-downloads version: 0.1.8

**Comment by elaichenkov** [comment]
Hey,
Thanks for filling the issue! What's the node version you use? Have you added all the needed code in the `cypress/support/e2e.js` and in the `cypress.config.js`? Can you please attach screenshots of these files and the test?

**Comment by ayingyong** [comment]
Hey! Sure. here are the information related:
Node version : 14.15.5
cypress/support/e2e.js
![image](https://user-images.githubusercontent.com/64765489/186696048-888ba12a-0978-474d-b56f-4b0f0773ba68.png)
cypress.config.js
![image](https://user-images.githubusercontent.com/64765489/186696419-b85a6e6d-0f34-469e-be8e-8c84f9f249db.png)
Test
![image](https://user-images.githubusercontent.com/64765489/186696745-36147de4-2690-48f3-b29b-a2fbcf76de8b.png)

**Comment by elaichenkov** [comment]
Would you mind sharing the repository that exhibits the issue?

**Comment by ayingyong** [comment]
@elaichenkov , hi,sorry for late reply. let me try do re-create back in different repo (current is private project )

**Comment by elaichenkov** [comment]
> @elaichenkov , hi,sorry for late reply. here's the repo for your reference https://github.com/ayingyong/sample-repo-verify-download

Thank you! I'll take a look at it today.

**Comment by elaichenkov** [comment]
Hey,
I had a chance to take a look at the repo. I've found the issue, the problem is in the esbuild. So, to solve the problem you have to install `@esbuild-plugins/node-modules-polyfill` package and then added it to your `createBundler` function.

```diff
// support/e2e.js
const { defineConfig } = require("cypress");
const createBundler = require("@bahmutov/cypress-esbuild-preprocessor");
const addCucumberPreprocessorPlugin =
  require("@badeball/cypress-cucumber-preprocessor").addCucumberPreprocessorPlugin;
const createEsbuildPlugin =
  require("@badeball/cypress-cucumber-preprocessor/esbuild").createEsbuildPlugin;

// import the polyfill
+ const { NodeModulesPolyfillPlugin } = require('@esbuild-plugins/node-modules-polyfill');

module.exports = defineConfig({
  e2e: {
    async setupNodeEvents(on, config) {
      const bundler = createBundler({
-        plugins: [createEsbuildPlugin(config)],
+        plugins: [NodeModulesPolyfillPlugin(), createEsbuildPlugin(config)],
      });

      on("file:preprocessor", bundler);
      await addCucumberPreprocessorPlugin(on, config);

      on('task', { isFileExist, findFiles });

      return config;
    },
    specPattern: "cypress/e2e/features/*.feature",
    baseUrl: "https://demoqa.com/upload-download",
    chromeWebSecurity: false,
  },
});
```

Hope it helps you. Don't forget to hit the star button for the project.

**Comment by ayingyong** [comment]
Hi @elaichenkov , its worked perfectly! thank you so much! 👍
