### ISSUE TITLE
.crdownload will pass the verification with {contains: true}

### ISSUE THREAD

**Issue by PhilipAllStar** [elaichenkov/cy-verify-downloads#55]
When downloading a file in google Chrome the ending .crdownlaod gets appended to the downloaded file and removed when the file is downloaded completly. The file is already in the downloads folder when first downloaded.

### Example
`01_01_22_text.txt.crdownload` will pass `cy.verifyDownload('text.txt', {contains: true, timeout: 10000, interval: 250});` even though it is still downloading the file.

### Expected behaviour
Only let files pass that are fully downloaded to ensure they are really downloaded. After the validation with the plugin the contents of the file can be validated.

**Comment by elaichenkov** [comment]
Hey @PhilipAllStar,
Thanks for filling the issue. It's definitely a bug. I'll create a fix for that and publish it later today.

**Comment by elaichenkov** [comment]
I've fixed and released it in the 0.1.9 version. So, update the package and enjoy. Also, don't forget to hit the star button for the project.
