### ISSUE TITLE
Adding a timeout option does not wait enough as it should

### ISSUE THREAD

**Issue by muayadsalah** [elaichenkov/cy-verify-downloads#64]
I have a heavy file download operation, that on Jenkins takes more than a minute to fully have the file downloaded, so I counted on setting the timeout option to some high value, around 2 minutes, but it just didn't wait till then. It always waits for 60 seconds no matter how big/small my timeout is

**Comment by elaichenkov** [comment]
Hey,
Have you tried to increase test timeout in config or for the specific test?

Try this one:
```js
// cypress.config.js
const { defineConfig } = require('cypress')

module.exports = defineConfig({
  defaultCommandTimeout: 90000
})
```

or this:
```js
download.cy.js
it('should download file with large timeout', {defaultCommandTimeout: 90000 }, () => {
  // ...
})
```

**Comment by muayadsalah** [comment]
I'll try it out and let you know, thanks

**Comment by muayadsalah** [comment]
It worked :D thanks
