### ISSUE TITLE
TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by victoriajuan** [elaichenkov/cy-verify-downloads#67]
Running the test with `verifyDownload` but got this error. Using all default though so I'm not sure when did the file path got wrong. Any idea?
<img width="819" alt="Screen Shot 2022-10-27 at 1 06 08 AM" src="https://user-images.githubusercontent.com/22421922/198227532-3b43c499-0887-4b8e-b937-0c0e9c1c4387.png">

**Comment by elaichenkov** [comment]
It seems that you're providing not a string to the method. I'm closing it. However, feel free to reopen the issue with reproducible examples.
