### ISSUE TITLE
Runs into timeout in case the downloaded filename includes spaces on Linux systems

### ISSUE THREAD

**Issue by BrunnerLivio** [elaichenkov/cy-verify-downloads#79]
Given the following command:

```typescript
cy.verifyDownload(`report 2018-11-30.csv`, {
  timeout: 500,
})
```

The test will fail with:
 
```
Due to couldn't find report 2018-11-30.csv file in ...cypress/downloads folder
...
```

This works on MacOS though

**Comment by BrunnerLivio** [comment]
I was able to workaround this issue by including backspace:

```typescript
cy.verifyDownload(`report\ 2018-11-30.csv`, {
  timeout: 500,
})
```

**Comment by elaichenkov** [comment]
Hey,
Thanks for creating the issue. However, this is not related to the library. If you want to deal with spaces in the path then you need to escape spaces with a backslash.
