### ISSUE TITLE
Errors for initialize the module : path, fs and crypto missing

### ISSUE THREAD

**Issue by RachelDSS** [elaichenkov/cy-verify-downloads#83]
I follow the documentation to use the cy-verify-downloads module. 
But when I run my test I have this error : 

![image](https://user-images.githubusercontent.com/17544724/213750815-4f4ac2ab-d57e-40f3-bb31-aca06864d4ba.png)

Do you know how fix it ? 

I tried to install dependencies, it work for "path" but didn't work for others.

Cypress version : 11.1.0

**Comment by elaichenkov** [comment]
Hey,

It seems like `esbuild` issue. Moreover, you don't have to install any dependencies additionally. You just need to add a polyfill for the node. Try to do this:
https://github.com/elaichenkov/cy-verify-downloads/issues/51#issuecomment-1237978973

**Comment by RachelDSS** [comment]
Thanks ! 
I added polyfill and now it work :)

**Comment by DavidAtImpactCubed** [comment]
I ran into the same problem recently. I would think anyone using the cucumber pre-processor will probably trip at the same point. Maybe worth adding a note to the installation readme?

**Comment by elaichenkov** [comment]
@DavidAtImpactCubed 
I thought about it but then decided not to add it because it's more about setting up the preprocessor. However, I'll add this information to the documentation. Thanks you!

**Comment by DavidAtImpactCubed** [comment]
I've proposed a change in case it helps.
